export const ADVANCE_SOFTWARE_ENGINEERING = "ADVANCE_SOFTWARE_ENGINEERING";

export const CYBER_SECURITY_AND_BLOCKCHAIN = "CYBER_SECURITY_AND_BLOCKCHAIN";

export const WEB_DEVELOPMENT_USING_DOTNET = "WEB_DEVELOPMENT_USING_DOTNET";

export const MACHINE_LEARNING_AND_PYTHON_PROGRAMMING = "MACHINE_LEARNING_AND_PYTHON_PROGRAMMING";

export const IOT_AND_SENSOR_NETWORK = "IOT_AND_SENSOR_NETWORK";
